// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "00 Hola Mundo.h"

/**
 Función Global Inicial
*/
Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(245, 160);
    w = o; if (w) {/* empty */}
    { Fl_Group* o = new Fl_Group(10, 25, 225, 130, "Grupo");
      { new Fl_Text_Display(20, 50, 205, 50, "Texto");
      } // Fl_Text_Display* o
      { new Fl_Button(35, 115, 175, 35, "Ejecutar");
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
