// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef _00_Hola_Mundo_h
#define _00_Hola_Mundo_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
#endif
